`default_nettype none

module am4_package_pins (
    output wire a04, // DP0_TXN[2]
    inout wire a05, // RSVD
    output wire a07, // DP2_TXP[1]
    output wire a08, // DP2_TXN[1]
    inout wire a10, // DP2_AUXP
    inout wire a11, // DP2_AUXN
    inout wire a13, // TEST11
    input wire a14, // TDI
    inout wire a16, // TEST41
    input wire a17, // SVT
    inout wire a19, // THERMTRIP_L
    inout wire a20, // ddr_b_data[4]
    inout wire a22, // ddr_b_dqs_l[0]
    inout wire a23, // ddr_b_data[6]
    inout wire a25, // ddr_b_data[12]
    inout wire a26, // ddr_b_data[8]
    inout wire a28, // ddr_b_data[14]
    inout wire a29, // ddr_b_data[10]
    inout wire a31, // ddr_b_data[16]
    inout wire a32, // ddr_b_dm[2]
    inout wire a34, // ddr_b_data[23]
    inout wire a35, // ddr_b_data[28]
    inout wire a37, // ddr_b_dqs_l[3]
    input wire aa02, // USB_SS_1RXP
    input wire aa03, // USB_SS_1RXN
    output wire aa05, // P_HUB_TXP[1]
    input wire aa08, // P_HUB_RXN[1]
    inout wire aa30, // TEST31
    output wire aa32, // ddr_a_add[0]
    output wire aa33, // ddr_a_bank[1]
    output wire aa35, // ddr_a_bank[0]
    output wire aa36, // ddr_a_add[10]
    input wire aa38, // ddr_b_event_l
    output wire aa39, // ddr_b_clk_l[3]
    output wire ab01, // USB_SS_1TXP
    inout wire ab02, // RSVD
    inout wire ab04, // TEST10
    output wire ab05, // P_HUB_TXN[1]
    input wire ab08, // P_HUB_RXP[1]
    output wire ab34, // ddr_a_ras_l_add[16]
    output wire ab35, // ddr_a_we_l_add[14]
    inout wire ab37, // RSVD
    output wire ab38, // ddr_b_parout
    output wire ac01, // USB_SS_1TXN
    output wire ac03, // USB_SS_2TXP
    output wire ac04, // USB_SS_2TXN
    output wire ac06, // P_HUB_TXP[2]
    output wire ac07, // P_HUB_TXN[2]
    output wire ac33, // ddr_a0_cs_l[0]
    output wire ac34, // ddr_a1_cs_l[0]
    output wire ac36, // ddr_b_add[0]
    output wire ac37, // ddr_b_bank[1]
    output wire ac39, // ddr_b_add[10]
    input wire ad02, // USB_SS_2RXP
    inout wire ad03, // RSVD
    output wire ad05, // P_HUB_TXP[3]
    output wire ad06, // P_HUB_TXN[3]
    input wire ad08, // P_HUB_RXN[0]
    output wire ad32, // ddr_a_cas_l_add[15]
    output wire ad33, // ddr_a1_odt[0]
    output wire ad35, // ddr_a0_odt[0]
    output wire ad36, // ddr_b_ras_l_add[16]
    output wire ad38, // ddr_b_bank[0]
    output wire ad39, // ddr_b_we_l_add[14]
    input wire ae01, // USB_SS_3RXP
    input wire ae02, // USB_SS_2RXN
    output wire ae04, // P_HUB_TXP[0]
    output wire ae05, // P_HUB_TXN[0]
    input wire ae08, // P_HUB_RXP[0]
    output wire ae32, // ddr_a_add[13]
    output wire ae34, // ddr_a1_cs_l[1]
    output wire ae35, // ddr_a0_cs_l[1]
    output wire ae37, // ddr_b0_cs_l[0]
    output wire ae38, // ddr_b1_cs_l[0]
    input wire af01, // USB_SS_3RXN
    output wire af03, // USB_SS_0TXP
    output wire af04, // USB_SS_0TXN
    output wire af06, // GFX_CLKP
    output wire af07, // GFX_CLKN
    output wire af31, // ddr_a0_odt[1]
    output wire af33, // ddr_a_add_17
    output wire af34, // ddr_a1_odt[1]
    output wire af36, // ddr_b_cas_l_add[15]
    output wire af37, // ddr_b1_odt[0]
    output wire af39, // ddr_b0_odt[0]
    output wire ag02, // USB_SS_3TXP
    output wire ag03, // USB_SS_3TXN
    output wire ag05, // GPP_CLK0P
    output wire ag06, // GPP_CLK0N
    output wire ag36, // ddr_b1_cs_l[1]
    output wire ag38, // ddr_b_add[13]
    output wire ag39, // ddr_b0_cs_l[1]
    inout wire ah01, // X48M_X2
    inout wire ah02, // RSVD
    output wire ah04, // GPP_CLK1P
    output wire ah05, // GPP_CLK1N
    output wire ah07, // GPP_CLK2P
    output wire ah08, // GPP_CLK2N
    inout wire ah31, // ddr_a_data[36]
    inout wire ah32, // ddr_a_data[37]
    inout wire ah34, // ddr_a_data[32]
    inout wire ah35, // RSVD
    output wire ah36, // ddr_b0_odt[1]
    output wire ah37, // ddr_b_add_17
    output wire ah38, // ddr_b1_odt[1]
    inout wire aj01, // X48M_X1
    inout wire aj03, // USB0_ZVSS
    inout wire aj04, // USB_SS_ZVSS
    output wire aj06, // GPP_CLK3P
    output wire aj07, // GPP_CLK3N
    inout wire aj30, // ddr_a_data[33]
    inout wire aj31, // ddr_a_dm[4]
    inout wire aj33, // ddr_a_dqs_h[4]
    inout wire aj34, // ddr_a_dqs_l[4]
    inout wire aj37, // ddr_a_zvss
    inout wire aj39, // ddr_b_zvss
    inout wire ak02, // SDA1/I2C3_SDA/AGPIO20
    inout wire ak03, // SCL1/I2C3_SCL/AGPIO19
    inout wire ak05, // USB3_ZVSS
    inout wire ak06, // USB2_ZVSS
    inout wire ak26, // ddr_a_data[57]
    inout wire ak27, // ddr_a_data[56]
    inout wire ak29, // ddr_a_data[49]
    inout wire ak30, // ddr_a_data[34]
    inout wire ak32, // ddr_a_data[39]
    inout wire ak33, // ddr_a_data[38]
    inout wire ak34, // RSVD
    inout wire ak36, // ddr_b_data[37]
    inout wire ak38, // ddr_b_data[36]
    inout wire ak39, // ddr_b_data[32]
    input wire al01, // USB_OC0_L/AGPIO16
    inout wire al02, // LPC_PME_L/AGPIO22
    inout wire al04, // TEST46[13]
    input wire al05, // WAKE_L/AGPIO2
    output wire al07, // PCIE_RST_L/EGPIO26
    output wire al08, // AM4R1
    output wire al13, // P_GPP_TXP[2]/SATA_TX0P
    inout wire al16, // RSVD
    inout wire al17, // RSVD
    inout wire al18, // RSVD
    inout wire al19, // RSVD
    inout wire al20, // RSVD
    inout wire al21, // RSVD
    input wire al23, // CLK_REQ3_L/SATA_IS1_L/SATA_ZP1_L/EGPIO131
    inout wire al25, // ddr_a_data[62]
    inout wire al26, // ddr_a_dm[7]
    inout wire al28, // ddr_a_data[51]
    inout wire al29, // ddr_a_dm[6]
    inout wire al31, // ddr_a_data[45]
    inout wire al32, // ddr_a_data[44]
    inout wire al34, // ddr_a_data[35]
    inout wire al37, // ddr_b_data[33]
    inout wire al38, // ddr_b_dm[4]
    input wire am01, // USB_OC1_L/TDI/AGPIO17
    input wire am03, // PWR_GOOD
    input wire am04, // SYS_RESET_L/AGPIO1
    inout wire am06, // TEST0
    inout wire am07, // TEST1/TMS
    input wire am09, // P_GPP_RXP[1]
    input wire am10, // P_GPP_RXN[1]
    inout wire am12, // RSVD
    output wire am13, // P_GPP_TXN[2]/SATA_TX0N
    inout wire am16, // RSVD
    inout wire am17, // RSVD
    inout wire am21, // RSVD
    output wire am22, // SATA_ACT_L/AGPIO130
    output wire am24, // CORETYPE[0]
    inout wire am25, // ddr_a_data[63]
    inout wire am27, // ddr_a_data[61]
    inout wire am28, // ddr_a_data[50]
    inout wire am30, // ddr_a_data[52]
    inout wire am31, // ddr_a_dm[5]
    inout wire am33, // ddr_a_data[41]
    inout wire am34, // ddr_a_data[40]
    inout wire am36, // ddr_b_dqs_l[4]
    inout wire am37, // ddr_b_dqs_h[4]
    inout wire am39, // ddr_b_data[38]
    inout wire an02, // AGPIO9/SGPIO0_DATAOUT
    inout wire an03, // AGPIO23/SGPIO0_LOAD
    input wire an05, // PWR_BTN_L/AGPIO0
    inout wire an06, // USB1_ZVSS
    inout wire an08, // AGPIO6
    output wire an09, // CORETYPE[1]
    input wire an11, // P_GPP_RXN[3]/SATA_RX1N
    inout wire an12, // RSVD
    output wire an14, // P_GPP_TXP[3]/SATA_TX1P
    inout wire an15, // RSVD
    inout wire an16, // RSVD
    inout wire an17, // RSVD
    inout wire an21, // RSVD
    input wire an23, // FANIN0/AGPIO84
    inout wire an24, // ESPI_RESET_L/KBRST_L
    inout wire an26, // ddr_a_dqs_l[7]
    inout wire an27, // ddr_a_data[60]
    inout wire an29, // ddr_a_dqs_l[6]
    inout wire an30, // ddr_a_data[53]
    inout wire an32, // ddr_a_dqs_h[5]
    inout wire an33, // ddr_a_dqs_l[5]
    inout wire an36, // ddr_b_data[34]
    inout wire an38, // ddr_b_data[39]
    inout wire an39, // ddr_b_data[35]
    inout wire ap01, // USB_OC3_L/TDO/AGPIO24
    output wire ap02, // SLP_S5_L
    output wire ap04, // S5_MUX_CTRL/EGPIO42
    input wire ap05, // RSMRST_L
    inout wire ap07, // AGPIO8
    output wire ap08, // RTCCLK
    input wire ap10, // P_GPP_RXN[2]/SATA_RX0N
    input wire ap11, // P_GPP_RXP[3]/SATA_RX1P
    output wire ap13, // P_GPP_TXP[1]
    output wire ap14, // P_GPP_TXN[3]/SATA_TX1N
    inout wire ap15, // RSVD
    inout wire ap16, // RSVD
    inout wire ap17, // RSVD
    inout wire ap21, // RSVD
    inout wire ap22, // AGPIO5/DEVSLP0
    output wire ap23, // FANOUT0/AGPIO85
    inout wire ap25, // ddr_a_data[58]
    inout wire ap26, // ddr_a_dqs_h[7]
    inout wire ap28, // ddr_a_data[54]
    inout wire ap29, // ddr_a_dqs_h[6]
    inout wire ap31, // ddr_a_data[42]
    inout wire ap32, // ddr_a_data[47]
    inout wire ap34, // ddr_a_data[46]
    inout wire ap37, // ddr_b_data[44]
    inout wire ap38, // ddr_b_data[45]
    input wire ar01, // USB_OC2_L/TCK/AGPIO18
    inout wire ar03, // S0A3_GPIO/AGPIO10/SGPIO0_CLK
    inout wire ar04, // AGPIO40/SGPIO0_DATAIN
    inout wire ar06, // AGPIO4
    output wire ar07, // 48M_OSC
    input wire ar09, // P_GPP_RXP[0]
    input wire ar10, // P_GPP_RXP[2]/SATA_RX0P
    output wire ar12, // P_GPP_TXN[0]
    output wire ar13, // P_GPP_TXN[1]
    inout wire ar15, // RSVD
    inout wire ar16, // RSVD
    inout wire ar18, // RSVD
    inout wire ar19, // RSVD
    inout wire ar20, // RSVD
    inout wire ar21, // RSVD
    input wire ar22, // CLK_REQG_L/OSCIN/EGPIO132
    inout wire ar24, // RSVD
    inout wire ar25, // ddr_a_data[59]
    inout wire ar28, // ddr_a_data[55]
    inout wire ar31, // ddr_a_data[48]
    inout wire ar33, // ddr_a_data[43]
    inout wire ar36, // ddr_b_data[40]
    inout wire ar37, // ddr_b_data[41]
    inout wire ar39, // ddr_b_dm[5]
    output wire at02, // SLP_S3_L
    inout wire at03, // TEST2
    output wire at05, // BLINK/AGPIO11
    inout wire at06, // AGPIO3
    inout wire at08, // P0B_ZVSS
    input wire at09, // P_GPP_RXN[0]
    inout wire at11, // USB_ZVSS
    output wire at12, // P_GPP_TXP[0]
    inout wire at14, // EGPIO100
    inout wire at15, // ESPI_ALERT_L/LDRQ0_L/EGPIO108
    inout wire at17, // SPI_CS1_L/EGPIO118
    inout wire at18, // EGPIO70
    inout wire at19, // RSVD
    inout wire at20, // LAD3/EGPIO107
    inout wire at21, // LAD2/EGPIO106
    input wire at23, // CLK_REQ0_L/SATA_IS0_L/SATA_ZP0_L/AGPIO92
    input wire at24, // CLK_REQ2_L/AGPIO116
    inout wire at25, // RSVD
    inout wire at30, // RSVD
    inout wire at35, // ddr_b_dm[6]
    inout wire at36, // ddr_b_data[46]
    inout wire at38, // ddr_b_dqs_h[5]
    inout wire at39, // ddr_b_dqs_l[5]
    output wire au01, // AZ_RST_L
    output wire au02, // AZ_SYNC
    output wire au04, // AZ_SDOUT
    input wire au05, // AZ_SDIN1
    inout wire au07, // USB_HSD0P
    inout wire au08, // USB_HSD0N
    inout wire au10, // USB_HSD2P
    inout wire au11, // USB_HSD2N
    inout wire au13, // EGPIO98
    inout wire au14, // SPI_DI/ESPI_DAT1/EGPIO120
    inout wire au16, // SPI_DO/ESPI_DAT0/EGPIO121
    inout wire au17, // SPI_TPM_CS_L/AGPIO76
    output wire au19, // LPCCLK1/EGPIO75
    output wire au20, // LPCCLK0/EGPIO74
    inout wire au22, // LPC_RST_L
    input wire au23, // GENINT2_L/AGPIO90
    inout wire au25, // SCL0/I2C2_SCL/EGPIO113
    inout wire au28, // ddr_b_dqs_h[7]
    inout wire au29, // ddr_b_dqs_l[7]
    inout wire au31, // ddr_b_data[61]
    inout wire au32, // ddr_b_data[51]
    inout wire au34, // ddr_b_dqs_h[6]
    inout wire au35, // ddr_b_data[49]
    inout wire au37, // ddr_b_data[42]
    inout wire au38, // ddr_b_data[47]
    input wire av03, // AZ_SDIN0
    input wire av04, // AZ_SDIN2
    inout wire av06, // SATA_ZVSS
    inout wire av09, // USB_HSD3P
    inout wire av10, // USB_HSD3N
    inout wire av12, // EGPIO96
    inout wire av13, // EGPIO99
    inout wire av15, // SPI_HOLD_L/ESPI_DAT3/EGPIO133
    inout wire av16, // SPI_WP_L/ESPI_DAT2/EGPIO122
    inout wire av18, // LPC_PD_L/AGPIO21
    inout wire av19, // LPC_CLKRUN_L/AGPIO88
    inout wire av21, // LAD1/EGPIO105
    input wire av22, // GENINT1_L/AGPIO89
    input wire av24, // CLK_REQ1_L/AGPIO115
    inout wire av25, // SDA0/I2C2_SDA/EGPIO114
    inout wire av27, // ddr_b_data[63]
    inout wire av28, // ddr_b_data[62]
    inout wire av30, // ddr_b_data[57]
    inout wire av31, // ddr_b_data[60]
    inout wire av33, // ddr_b_data[55]
    inout wire av34, // ddr_b_dqs_l[6]
    inout wire av36, // ddr_b_data[52]
    inout wire av37, // ddr_b_data[43]
    output wire aw03, // AZ_BITCLK
    inout wire aw05, // X32K_X1
    inout wire aw06, // X32K_X2
    inout wire aw08, // USB_HSD1P
    inout wire aw09, // USB_HSD1N
    inout wire aw11, // EGPIO95
    inout wire aw12, // EGPIO97
    inout wire aw14, // SPI_CLK/ESPI_CLK/EGPIO117
    inout wire aw15, // SPI_CS2_L/ESPI_CS_L/EGPIO119
    inout wire aw17, // AGPIO86
    inout wire aw18, // LFRAME_L/EGPIO109
    inout wire aw20, // LAD0/EGPIO104
    inout wire aw21, // SERIRQ/AGPIO87
    output wire aw23, // SPKR/AGPIO91
    inout wire aw24, // RSVD
    inout wire aw26, // ddr_b_data[59]
    inout wire aw27, // ddr_b_data[58]
    inout wire aw29, // ddr_b_dm[7]
    inout wire aw30, // ddr_b_data[56]
    inout wire aw32, // ddr_b_data[50]
    inout wire aw33, // ddr_b_data[54]
    inout wire aw35, // ddr_b_data[48]
    inout wire aw36, // ddr_b_data[53]
    output wire b03, // DP0_TXN[1]
    output wire b04, // DP0_TXP[2]
    output wire b06, // DP2_TXP[0]
    output wire b07, // DP2_TXN[0]
    output wire b09, // DP2_TXP[3]
    output wire b10, // DP2_TXN[3]
    inout wire b12, // TEST15
    input wire b13, // TRST_L
    input wire b15, // TMS
    inout wire b16, // RESET_L
    output wire b18, // SIC
    inout wire b21, // ddr_b_data[1]
    inout wire b22, // ddr_b_dqs_h[0]
    inout wire b24, // ddr_b_data[2]
    inout wire b25, // ddr_b_data[13]
    inout wire b27, // ddr_b_dqs_l[1]
    inout wire b28, // ddr_b_data[15]
    inout wire b30, // ddr_b_data[20]
    inout wire b31, // ddr_b_data[17]
    inout wire b33, // ddr_b_data[22]
    inout wire b34, // ddr_b_data[18]
    inout wire b36, // ddr_b_data[24]
    inout wire b37, // ddr_b_dqs_h[3]
    inout wire b38, // ddr_b_data[30]
    output wire c02, // DP0_TXN[0]
    output wire c03, // DP0_TXP[1]
    output wire c05, // DP0_TXP[3]
    output wire c06, // DP0_TXN[3]
    output wire c08, // DP2_TXP[2]
    output wire c09, // DP2_TXN[2]
    inout wire c11, // TEST16
    inout wire c12, // TEST14
    output wire c14, // TDO
    input wire c15, // TCK
    inout wire c17, // SVD
    inout wire c18, // SID
    inout wire c20, // ddr_b_data[5]
    inout wire c21, // ddr_b_dm[0]
    inout wire c23, // ddr_b_data[7]
    inout wire c24, // ddr_b_data[3]
    inout wire c26, // ddr_b_data[9]
    inout wire c27, // ddr_b_dqs_h[1]
    inout wire c29, // ddr_b_data[11]
    inout wire c30, // ddr_b_data[21]
    inout wire c32, // ddr_b_dqs_l[2]
    inout wire c33, // ddr_b_dqs_h[2]
    inout wire c35, // ddr_b_data[19]
    inout wire c36, // ddr_b_data[29]
    inout wire c38, // ddr_b_data[31]
    inout wire c39, // ddr_b_data[26]
    output wire d01, // P_GFX_TXP[0]
    output wire d02, // DP0_TXP[0]
    output wire d04, // DP1_TXP[0]
    output wire d05, // DP1_TXN[0]
    output wire d07, // DP1_TXP[1]
    output wire d08, // DP1_TXN[1]
    input wire d10, // DP1_HPD
    inout wire d11, // TEST17
    inout wire d13, // TEST6
    input wire d14, // DBREQ_L
    input wire d16, // ALERT_L
    output wire d17, // SVC
    inout wire d20, // ddr_b_data[0]
    inout wire d26, // ddr_b_dm[1]
    inout wire d28, // RSVD
    inout wire d37, // ddr_b_dm[3]
    inout wire d38, // ddr_b_data[27]
    output wire e01, // P_GFX_TXN[0]
    output wire e03, // P_GFX_TXP[1]
    inout wire e06, // TEST28_H
    inout wire e07, // TEST28_L
    output wire e09, // DP1_TXP[3]
    input wire e10, // DP2_HPD
    inout wire e12, // DP_AUX_ZVSS
    output wire e13, // DBRDY
    output wire e16, // PWROK
    inout wire e18, // ddr_a_data[0]
    inout wire e19, // RSVD
    inout wire e22, // RSVD
    inout wire e24, // ddr_a_data[10]
    inout wire e25, // RSVD
    inout wire e28, // ddr_a_data[22]
    inout wire e30, // ddr_a_dqs_l[3]
    inout wire e31, // ddr_a_data[30]
    inout wire e33, // ddr_a_check[4]
    inout wire e34, // ddr_a_check[5]
    inout wire e36, // ddr_b_data[25]
    inout wire e37, // ddr_b_check[4]
    inout wire e39, // ddr_b_check[5]
    output wire f02, // P_GFX_TXP[2]
    output wire f03, // P_GFX_TXN[1]
    input wire f05, // P_GFX_RXN[0]
    input wire f06, // P_GFX_RXP[0]
    output wire f08, // DP1_TXP[2]
    output wire f09, // DP1_TXN[3]
    inout wire f11, // DP1_AUXP
    inout wire f12, // DP_ZVSS
    inout wire f18, // ddr_a_data[5]
    inout wire f20, // ddr_a_data[7]
    inout wire f21, // ddr_a_data[12]
    inout wire f23, // ddr_a_dqs_h[1]
    inout wire f24, // ddr_a_data[15]
    inout wire f26, // ddr_a_dqs_l[2]
    inout wire f27, // ddr_a_dqs_h[2]
    inout wire f29, // ddr_a_data[24]
    inout wire f30, // ddr_a_dqs_h[3]
    inout wire f32, // ddr_a_data[27]
    inout wire f33, // ddr_a_check[0]
    inout wire f36, // ddr_b_check[1]
    inout wire f38, // ddr_b_check[0]
    inout wire f39, // ddr_b_dm[8]
    output wire g01, // P_GFX_TXP[3]
    output wire g02, // P_GFX_TXN[2]
    input wire g04, // P_GFX_RXN[1]
    input wire g05, // P_GFX_RXP[1]
    output wire g08, // DP1_TXN[2]
    inout wire g10, // DP0_AUXP
    inout wire g11, // DP1_AUXN
    output wire g13, // DP_BLON
    inout wire g16, // TEST18
    inout wire g17, // RSVD
    inout wire g19, // ddr_a_dqs_l[0]
    inout wire g20, // ddr_a_data[6]
    inout wire g22, // ddr_a_data[9]
    inout wire g23, // ddr_a_dqs_l[1]
    inout wire g25, // ddr_a_data[21]
    inout wire g26, // ddr_a_dm[2]
    inout wire g28, // ddr_a_data[18]
    inout wire g29, // ddr_a_data[29]
    inout wire g31, // ddr_a_data[31]
    inout wire g32, // ddr_a_check[1]
    inout wire g34, // ddr_a_dm[8]
    inout wire g37, // ddr_b_dqs_l[8]
    inout wire g38, // ddr_b_dqs_h[8]
    output wire h01, // P_GFX_TXN[3]
    output wire h03, // P_GFX_TXP[4]
    input wire h06, // P_GFX_RXN[2]
    input wire h07, // P_GFX_RXP[2]
    input wire h09, // DP0_HPD
    inout wire h10, // DP0_AUXN
    output wire h12, // DP_VARY_BL
    output wire h13, // DP_DIGON
    input wire h15, // PROCHOT_L
    inout wire h16, // TEST19
    inout wire h18, // ddr_a_data[4]
    inout wire h19, // ddr_a_dqs_h[0]
    inout wire h21, // ddr_a_data[3]
    inout wire h22, // ddr_a_data[8]
    inout wire h24, // ddr_a_data[14]
    inout wire h25, // ddr_a_data[20]
    inout wire h27, // ddr_a_data[23]
    inout wire h28, // ddr_a_data[19]
    inout wire h30, // ddr_a_dm[3]
    inout wire h31, // ddr_a_data[26]
    inout wire h33, // ddr_a_dqs_l[8]
    inout wire h34, // ddr_a_dqs_h[8]
    inout wire h36, // ddr_b_check[6]
    inout wire h37, // ddr_b_check[7]
    inout wire h39, // ddr_b_check[2]
    output wire j02, // P_GFX_TXP[5]
    output wire j03, // P_GFX_TXN[4]
    input wire j05, // P_GFX_RXN[3]
    input wire j06, // P_GFX_RXP[3]
    inout wire j18, // ddr_a_data[1]
    inout wire j20, // ddr_a_data[2]
    inout wire j21, // ddr_a_data[13]
    inout wire j23, // ddr_a_dm[1]
    inout wire j24, // ddr_a_data[11]
    inout wire j26, // ddr_a_data[16]
    inout wire j27, // ddr_a_data[17]
    inout wire j29, // ddr_a_data[28]
    inout wire j30, // ddr_a_data[25]
    inout wire j32, // ddr_a_check[6]
    inout wire j33, // ddr_a_check[7]
    inout wire j36, // RSVD
    inout wire j38, // RSVD
    inout wire j39, // ddr_b_check[3]
    output wire k01, // P_GFX_TXP[6]
    output wire k02, // P_GFX_TXN[5]
    input wire k04, // P_GFX_RXN[5]
    input wire k05, // P_GFX_RXP[5]
    input wire k07, // P_GFX_RXN[4]
    input wire k08, // P_GFX_RXP[4]
    output wire k14, // DP_STEREOSYNC
    inout wire k19, // ddr_a_dm[0]
    inout wire k31, // ddr_a_check[2]
    inout wire k32, // ddr_a_check[3]
    inout wire k34, // RSVD
    output wire k35, // ddr_b_reset_l
    output wire k37, // ddr_b0_cke[1]
    inout wire k38, // RSVD
    output wire l01, // P_GFX_TXN[6]
    output wire l03, // P_GFX_TXP[7]
    input wire l06, // P_GFX_RXN[6]
    input wire l07, // P_GFX_RXP[6]
    inout wire l23, // TEST4
    output wire l33, // ddr_a_reset_l
    output wire l34, // ddr_a1_cke[1]
    output wire l36, // ddr_b1_cke[1]
    output wire l37, // ddr_b0_cke[0]
    output wire l39, // ddr_b1_cke[0]
    output wire m02, // P_GFX_TXP[8]
    output wire m03, // P_GFX_TXN[7]
    input wire m05, // P_GFX_RXN[7]
    input wire m06, // P_GFX_RXP[7]
    inout wire m22, // TEST5
    output wire m30, // ddr_a0_cke[1]
    output wire m32, // ddr_a0_cke[0]
    output wire m33, // ddr_a1_cke[0]
    output wire m35, // ddr_a_act_l
    output wire m36, // ddr_b_bg[0]
    output wire m38, // ddr_b_act_l
    output wire m39, // ddr_b_bg[1]
    output wire n01, // P_GFX_TXP[9]
    output wire n02, // P_GFX_TXN[8]
    input wire n04, // P_GFX_RXN[9]
    input wire n05, // P_GFX_RXP[9]
    input wire n07, // P_GFX_RXN[8]
    input wire n08, // P_GFX_RXP[8]
    output wire n31, // ddr_a_bg[0]
    output wire n32, // ddr_a_bg[1]
    output wire n34, // ddr_a_alert_l
    output wire n35, // ddr_a_add[12]
    output wire n37, // ddr_b_alert_l
    output wire n38, // ddr_b_add[12]
    output wire p01, // P_GFX_TXN[9]
    output wire p03, // P_GFX_TXP[10]
    input wire p06, // P_GFX_RXN[10]
    input wire p07, // P_GFX_RXP[10]
    inout wire p28, // TEST47
    output wire p30, // ddr_a_add[8]
    output wire p31, // ddr_a_add[9]
    output wire p33, // ddr_a_add[11]
    output wire p34, // ddr_a_add[7]
    output wire p36, // ddr_b_add[9]
    output wire p37, // ddr_b_add[11]
    output wire p39, // ddr_b_add[7]
    output wire r02, // P_GFX_TXP[11]
    output wire r03, // P_GFX_TXN[10]
    input wire r05, // P_GFX_RXN[11]
    input wire r06, // P_GFX_RXP[11]
    output wire r30, // ddr_a_add[4]
    output wire r32, // ddr_a_add[6]
    output wire r33, // ddr_a_add[5]
    inout wire r35, // RSVD
    output wire r36, // ddr_b_add[6]
    output wire r38, // ddr_b_add[8]
    output wire r39, // ddr_b_add[5]
    output wire t01, // P_GFX_TXP[12]
    output wire t02, // P_GFX_TXN[11]
    input wire t04, // P_GFX_RXP[13]
    input wire t05, // P_GFX_RXN[13]
    input wire t07, // P_GFX_RXN[12]
    input wire t08, // P_GFX_RXP[12]
    output wire t31, // ddr_a_add[3]
    output wire t32, // ddr_a_add[1]
    output wire t34, // ddr_a_clk_h[0]
    output wire t35, // ddr_a_add[2]
    output wire t37, // ddr_b_add[4]
    output wire t38, // ddr_b_add[3]
    output wire u01, // P_GFX_TXN[12]
    output wire u03, // P_GFX_TXP[13]
    input wire u06, // P_GFX_RXN[14]
    input wire u07, // P_GFX_RXP[14]
    output wire u33, // ddr_a_clk_h[1]
    output wire u34, // ddr_a_clk_l[0]
    output wire u36, // ddr_b_add[1]
    output wire u37, // ddr_b_add[2]
    output wire u39, // ddr_b_clk_h[0]
    output wire v02, // P_GFX_TXP[14]
    output wire v03, // P_GFX_TXN[13]
    input wire v05, // P_GFX_RXN[15]
    input wire v06, // P_GFX_RXP[15]
    inout wire v08, // P0A_ZVSS
    output wire v32, // ddr_a_clk_h[3]
    output wire v33, // ddr_a_clk_l[1]
    output wire v35, // ddr_a_clk_h[2]
    output wire v36, // ddr_a_clk_l[2]
    output wire v38, // ddr_b_clk_h[1]
    output wire v39, // ddr_b_clk_l[0]
    output wire w01, // P_GFX_TXP[15]
    output wire w02, // P_GFX_TXN[14]
    input wire w04, // P_HUB_RXP[3]
    input wire w05, // P_HUB_RXN[3]
    inout wire w07, // P_ZVSS
    inout wire w30, // TEST40
    output wire w32, // ddr_a_clk_l[3]
    input wire w35, // ddr_a_event_l
    output wire w37, // ddr_b_clk_h[2]
    output wire w38, // ddr_b_clk_l[1]
    output wire y01, // P_GFX_TXN[15]
    input wire y03, // USB_SS_0RXP
    input wire y04, // USB_SS_0RXN
    input wire y06, // P_HUB_RXP[2]
    input wire y07, // P_HUB_RXN[2]
    output wire y33, // ddr_a_parout
    output wire y37, // ddr_b_clk_l[2]
    output wire y39 // ddr_b_clk_h[3]
);
endmodule
